# Imagen base de Python
FROM python:3.10-slim

# Crear carpeta de la app
WORKDIR /app

# Copiar requerimientos
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Exponer el puerto del microservicio Flask
EXPOSE 5001

# Comando para ejecutar Flask
CMD ["python", "microservicioPedidos.py"]
